import type {
  Ad,
  AlertItem,
  CalendarPoint,
  Competitor,
  CompetitorId,
  InsightCardData,
  WordFreq,
} from "./types";

export const competitors: Competitor[] = [
  {
    id: "miso",
    name: "미소",
    logoColor: "#FFC940",
    primaryColor: "#FFC940",
    description: "홈클리닝 매칭 플랫폼",
  },
  {
    id: "soomgo",
    name: "숨고",
    logoColor: "#3D7AFE",
    primaryColor: "#3D7AFE",
    description: "생활 서비스 매칭",
  },
  {
    id: "laundrygo",
    name: "런드리고",
    logoColor: "#1ABC9C",
    primaryColor: "#1ABC9C",
    description: "비대면 세탁·청소",
  },
  {
    id: "yeolda",
    name: "열다",
    logoColor: "#FF6B6B",
    primaryColor: "#FF6B6B",
    description: "프리미엄 청소 서비스",
  },
];

const today = new Date("2026-05-06");
function daysAgo(n: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

// Picsum & Unsplash-style placeholders (using picsum which is reliable)
function pic(seed: string, w: number, h: number) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

export const ads: Ad[] = [
  // --- 미소 (8) ---
  {
    id: "miso-001",
    competitor: "miso",
    platform: "Meta",
    imageUrl: pic("miso1", 600, 600),
    aspectRatio: "1:1",
    copy: "✨ 깨끗한 집, 미소가 만들어드려요. 신규 가입 30% 할인!",
    imageText: "미소 첫 청소 30% OFF",
    cta: "지금 예약하기",
    firstSeen: daysAgo(28),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 28,
    format: "이미지",
    dominantColors: ["#FFC940", "#FFFFFF", "#2D2D2D", "#FFE699", "#A8895A"],
    textDensity: "Medium",
    visualType: "라이프스타일",
    themes: ["청결", "할인"],
    landingUrl: "https://miso.com/promo",
    tags: ["할인", "신규가입"],
  },
  {
    id: "miso-002",
    competitor: "miso",
    platform: "Meta",
    imageUrl: pic("miso2", 600, 1067),
    aspectRatio: "9:16",
    copy: "👨‍👩‍👧‍👦 바쁜 워킹맘을 위한 정기청소. 매주 같은 도우미가 와요.",
    imageText: "워킹맘의 든든한 친구",
    cta: "정기 청소 시작",
    firstSeen: daysAgo(21),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 21,
    format: "동영상",
    dominantColors: ["#FFC940", "#F5E1A4", "#FFFFFF", "#3D2D1F", "#D4B068"],
    textDensity: "Minimal",
    visualType: "인물",
    themes: ["가족", "신뢰"],
    landingUrl: "https://miso.com/regular",
    tags: ["정기청소"],
  },
  {
    id: "miso-003",
    competitor: "miso",
    platform: "Google",
    imageUrl: pic("miso3", 600, 600),
    aspectRatio: "1:1",
    copy: "전문 청소 매니저가 직접 방문. 100% 만족 보장.",
    imageText: "전문 매니저 보장",
    cta: "견적 받기",
    firstSeen: daysAgo(45),
    lastSeen: daysAgo(2),
    isActive: false,
    lifespanDays: 43,
    format: "이미지",
    dominantColors: ["#FFC940", "#FFFFFF", "#2D2D2D", "#888888", "#FFE699"],
    textDensity: "Heavy",
    visualType: "인물",
    themes: ["전문가", "신뢰"],
    landingUrl: "https://miso.com/quote",
    tags: ["견적"],
  },
  {
    id: "miso-004",
    competitor: "miso",
    platform: "TikTok",
    imageUrl: pic("miso4", 600, 1067),
    aspectRatio: "9:16",
    copy: "🤯 청소 전후 비교 영상! 이 정도일 줄 몰랐어요.",
    imageText: "BEFORE → AFTER",
    cta: "지금 신청",
    firstSeen: daysAgo(14),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 14,
    format: "동영상",
    dominantColors: ["#FFC940", "#7CB342", "#FFFFFF", "#5D4037", "#C0CA33"],
    textDensity: "Heavy",
    visualType: "Before-After",
    themes: ["변화", "후기"],
    landingUrl: "https://miso.com/before-after",
    tags: ["후기", "Before-After"],
  },
  {
    id: "miso-005",
    competitor: "miso",
    platform: "Meta",
    imageUrl: pic("miso5", 600, 750),
    aspectRatio: "4:5",
    copy: "이사 후 입주청소, 미소가 완벽하게.",
    imageText: "입주청소 NO.1",
    cta: "예약하기",
    firstSeen: daysAgo(7),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 7,
    format: "이미지",
    dominantColors: ["#FFC940", "#FFFFFF", "#2D2D2D", "#A8895A", "#FFE699"],
    textDensity: "Medium",
    visualType: "라이프스타일",
    themes: ["청결", "전문가"],
    landingUrl: "https://miso.com/move-in",
    tags: ["입주청소"],
  },
  {
    id: "miso-006",
    competitor: "miso",
    platform: "Meta",
    imageUrl: pic("miso6", 600, 600),
    aspectRatio: "1:1",
    copy: "5만 건 후기가 증명하는 미소의 만족도.",
    imageText: "★ 4.9 / 5만+ 후기",
    cta: "후기 보기",
    firstSeen: daysAgo(3),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 3,
    format: "이미지",
    dominantColors: ["#FFC940", "#FFFFFF", "#FFB300", "#2D2D2D", "#888888"],
    textDensity: "Medium",
    visualType: "인포그래픽",
    themes: ["후기", "신뢰"],
    landingUrl: "https://miso.com/reviews",
    tags: ["후기"],
  },
  {
    id: "miso-007",
    competitor: "miso",
    platform: "Google",
    imageUrl: pic("miso7", 1200, 675),
    aspectRatio: "16:9",
    copy: "에어컨 청소도 미소에서. 시즌 한정 20% 할인.",
    imageText: "에어컨 청소 -20%",
    cta: "할인 받기",
    firstSeen: daysAgo(10),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 10,
    format: "이미지",
    dominantColors: ["#FFC940", "#42A5F5", "#FFFFFF", "#2D2D2D", "#90CAF9"],
    textDensity: "Heavy",
    visualType: "제품샷",
    themes: ["할인", "전문가"],
    landingUrl: "https://miso.com/aircon",
    tags: ["에어컨", "할인"],
  },
  {
    id: "miso-008",
    competitor: "miso",
    platform: "Meta",
    imageUrl: pic("miso8", 600, 600),
    aspectRatio: "1:1",
    copy: "📱 미소 앱 다운로드하고 청소 비용 결제까지 한 번에.",
    imageText: "앱으로 더 쉽게",
    cta: "앱 다운로드",
    firstSeen: daysAgo(35),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 35,
    format: "캐러셀",
    dominantColors: ["#FFC940", "#FFFFFF", "#FFE699", "#2D2D2D", "#FFB300"],
    textDensity: "Medium",
    visualType: "제품샷",
    themes: ["전문가"],
    landingUrl: "https://miso.com/app",
    tags: ["앱"],
  },

  // --- 숨고 (8) ---
  {
    id: "soomgo-001",
    competitor: "soomgo",
    platform: "Meta",
    imageUrl: pic("soomgo1", 600, 600),
    aspectRatio: "1:1",
    copy: "🔵 숨은 청소 고수들이 모인 곳, 숨고. 견적 비교하고 선택하세요.",
    imageText: "여러 견적, 한 번에",
    cta: "무료 견적 받기",
    firstSeen: daysAgo(40),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 40,
    format: "이미지",
    dominantColors: ["#3D7AFE", "#FFFFFF", "#1A4FCC", "#90CAF9", "#2D2D2D"],
    textDensity: "Heavy",
    visualType: "인포그래픽",
    themes: ["전문가"],
    landingUrl: "https://soomgo.com/quote",
    tags: ["견적", "비교"],
  },
  {
    id: "soomgo-002",
    competitor: "soomgo",
    platform: "Meta",
    imageUrl: pic("soomgo2", 600, 1067),
    aspectRatio: "9:16",
    copy: "전문가 평점 4.8 이상만 매칭. 검증된 청소 매니저만.",
    imageText: "★ 4.8+ 검증",
    cta: "지금 시작",
    firstSeen: daysAgo(18),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 18,
    format: "이미지",
    dominantColors: ["#3D7AFE", "#FFFFFF", "#90CAF9", "#0D47A1", "#E3F2FD"],
    textDensity: "Medium",
    visualType: "인물",
    themes: ["신뢰", "전문가"],
    landingUrl: "https://soomgo.com/pro",
    tags: ["전문가"],
  },
  {
    id: "soomgo-003",
    competitor: "soomgo",
    platform: "Google",
    imageUrl: pic("soomgo3", 1200, 675),
    aspectRatio: "16:9",
    copy: "이사청소·정기청소·에어컨까지, 숨고 하나로 끝.",
    imageText: "한 번에 모두",
    cta: "서비스 보기",
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 60,
    format: "이미지",
    dominantColors: ["#3D7AFE", "#FFFFFF", "#0D47A1", "#1976D2", "#90CAF9"],
    textDensity: "Heavy",
    visualType: "인포그래픽",
    themes: ["전문가"],
    landingUrl: "https://soomgo.com/services",
    tags: ["종합"],
  },
  {
    id: "soomgo-004",
    competitor: "soomgo",
    platform: "TikTok",
    imageUrl: pic("soomgo4", 600, 1067),
    aspectRatio: "9:16",
    copy: "👀 청소 고수의 작업 과정 라이브. 기술 차이가 보입니다.",
    imageText: "PRO의 손길",
    cta: "예약하기",
    firstSeen: daysAgo(12),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 12,
    format: "동영상",
    dominantColors: ["#3D7AFE", "#FFFFFF", "#FFC107", "#0D47A1", "#212121"],
    textDensity: "Minimal",
    visualType: "인물",
    themes: ["전문가", "변화"],
    landingUrl: "https://soomgo.com/live",
    tags: ["전문가"],
  },
  {
    id: "soomgo-005",
    competitor: "soomgo",
    platform: "Meta",
    imageUrl: pic("soomgo5", 600, 750),
    aspectRatio: "4:5",
    copy: "💬 실제 후기 모음. 4.8점 청소 매니저들의 비결.",
    imageText: "리얼 후기",
    cta: "후기 더보기",
    firstSeen: daysAgo(25),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 25,
    format: "캐러셀",
    dominantColors: ["#3D7AFE", "#FFFFFF", "#FFC107", "#90CAF9", "#0D47A1"],
    textDensity: "Heavy",
    visualType: "인포그래픽",
    themes: ["후기", "신뢰"],
    landingUrl: "https://soomgo.com/reviews",
    tags: ["후기"],
  },
  {
    id: "soomgo-006",
    competitor: "soomgo",
    platform: "Meta",
    imageUrl: pic("soomgo6", 600, 600),
    aspectRatio: "1:1",
    copy: "이사 D-7. 입주청소 견적 무료로 받아보세요.",
    imageText: "이사 D-7 체크",
    cta: "견적 받기",
    firstSeen: daysAgo(5),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 5,
    format: "이미지",
    dominantColors: ["#3D7AFE", "#FFFFFF", "#FFC107", "#0D47A1", "#212121"],
    textDensity: "Medium",
    visualType: "인포그래픽",
    themes: ["청결", "전문가"],
    landingUrl: "https://soomgo.com/move",
    tags: ["입주청소"],
  },
  {
    id: "soomgo-007",
    competitor: "soomgo",
    platform: "Google",
    imageUrl: pic("soomgo7", 600, 600),
    aspectRatio: "1:1",
    copy: "오늘 신청, 내일 청소. 빠른 매칭의 숨고.",
    imageText: "TODAY → TOMORROW",
    cta: "빠른 매칭",
    firstSeen: daysAgo(50),
    lastSeen: daysAgo(1),
    isActive: false,
    lifespanDays: 49,
    format: "이미지",
    dominantColors: ["#3D7AFE", "#FFFFFF", "#FFC107", "#0D47A1", "#90CAF9"],
    textDensity: "Heavy",
    visualType: "인포그래픽",
    themes: ["변화"],
    landingUrl: "https://soomgo.com/fast",
    tags: ["빠른매칭"],
  },
  {
    id: "soomgo-008",
    competitor: "soomgo",
    platform: "Meta",
    imageUrl: pic("soomgo8", 600, 1067),
    aspectRatio: "9:16",
    copy: "신혼집 입주청소, 견적 비교로 30% 아꼈어요.",
    imageText: "30% 절약 후기",
    cta: "견적 비교",
    firstSeen: daysAgo(8),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 8,
    format: "동영상",
    dominantColors: ["#3D7AFE", "#FFB6C1", "#FFFFFF", "#90CAF9", "#0D47A1"],
    textDensity: "Heavy",
    visualType: "인물",
    themes: ["할인", "후기"],
    landingUrl: "https://soomgo.com/newlywed",
    tags: ["신혼", "할인"],
  },

  // --- 런드리고 (6) ---
  {
    id: "laundrygo-001",
    competitor: "laundrygo",
    platform: "Meta",
    imageUrl: pic("laundrygo1", 600, 600),
    aspectRatio: "1:1",
    copy: "🧺 비대면 세탁 + 청소. 문 앞에 두면 끝.",
    imageText: "문 앞에 두면 끝",
    cta: "주문하기",
    firstSeen: daysAgo(33),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 33,
    format: "이미지",
    dominantColors: ["#1ABC9C", "#FFFFFF", "#16A085", "#A4E5DA", "#212121"],
    textDensity: "Minimal",
    visualType: "제품샷",
    themes: ["청결", "변화"],
    landingUrl: "https://laundrygo.com",
    tags: ["비대면"],
  },
  {
    id: "laundrygo-002",
    competitor: "laundrygo",
    platform: "Meta",
    imageUrl: pic("laundrygo2", 600, 750),
    aspectRatio: "4:5",
    copy: "런드리고 프리미엄 클리닝, 호텔식 마감.",
    imageText: "호텔식 마감",
    cta: "프리미엄 시작",
    firstSeen: daysAgo(22),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 22,
    format: "이미지",
    dominantColors: ["#1ABC9C", "#FFFFFF", "#A4E5DA", "#16A085", "#0D5C50"],
    textDensity: "Medium",
    visualType: "제품샷",
    themes: ["전문가", "청결"],
    landingUrl: "https://laundrygo.com/premium",
    tags: ["프리미엄"],
  },
  {
    id: "laundrygo-003",
    competitor: "laundrygo",
    platform: "TikTok",
    imageUrl: pic("laundrygo3", 600, 1067),
    aspectRatio: "9:16",
    copy: "📦 더러운 옷 → 새 옷처럼. 비포 애프터 영상.",
    imageText: "더러운 옷 NEW",
    cta: "지금 주문",
    firstSeen: daysAgo(15),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 15,
    format: "동영상",
    dominantColors: ["#1ABC9C", "#FFFFFF", "#FF6F61", "#16A085", "#212121"],
    textDensity: "Heavy",
    visualType: "Before-After",
    themes: ["변화", "후기"],
    landingUrl: "https://laundrygo.com/before-after",
    tags: ["Before-After"],
  },
  {
    id: "laundrygo-004",
    competitor: "laundrygo",
    platform: "Google",
    imageUrl: pic("laundrygo4", 1200, 675),
    aspectRatio: "16:9",
    copy: "정기 구독으로 매주 깨끗한 옷. 첫 달 50% 할인.",
    imageText: "첫달 50% OFF",
    cta: "구독 시작",
    firstSeen: daysAgo(11),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 11,
    format: "이미지",
    dominantColors: ["#1ABC9C", "#FFFFFF", "#FF6F61", "#16A085", "#A4E5DA"],
    textDensity: "Heavy",
    visualType: "인포그래픽",
    themes: ["할인"],
    landingUrl: "https://laundrygo.com/sub",
    tags: ["구독", "할인"],
  },
  {
    id: "laundrygo-005",
    competitor: "laundrygo",
    platform: "Meta",
    imageUrl: pic("laundrygo5", 600, 600),
    aspectRatio: "1:1",
    copy: "🌱 친환경 세제만 사용. 아이가 있는 집도 안심.",
    imageText: "친환경·안심",
    cta: "더 알아보기",
    firstSeen: daysAgo(6),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 6,
    format: "이미지",
    dominantColors: ["#1ABC9C", "#FFFFFF", "#A4E5DA", "#7CB342", "#16A085"],
    textDensity: "Medium",
    visualType: "라이프스타일",
    themes: ["가족", "신뢰"],
    landingUrl: "https://laundrygo.com/eco",
    tags: ["친환경"],
  },
  {
    id: "laundrygo-006",
    competitor: "laundrygo",
    platform: "Meta",
    imageUrl: pic("laundrygo6", 600, 1067),
    aspectRatio: "9:16",
    copy: "주말은 세탁기 그만. 런드리고에 맡기고 쉬세요.",
    imageText: "주말은 쉬자",
    cta: "맡기기",
    firstSeen: daysAgo(2),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 2,
    format: "동영상",
    dominantColors: ["#1ABC9C", "#FFFFFF", "#A4E5DA", "#FFD54F", "#212121"],
    textDensity: "Minimal",
    visualType: "라이프스타일",
    themes: ["가족", "변화"],
    landingUrl: "https://laundrygo.com/weekend",
    tags: ["라이프"],
  },

  // --- 열다 (6) ---
  {
    id: "yeolda-001",
    competitor: "yeolda",
    platform: "Meta",
    imageUrl: pic("yeolda1", 600, 600),
    aspectRatio: "1:1",
    copy: "🌸 프리미엄 입주청소, 열다. VIP 케어 받아보세요.",
    imageText: "VIP 입주청소",
    cta: "프리미엄 예약",
    firstSeen: daysAgo(20),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 20,
    format: "이미지",
    dominantColors: ["#FF6B6B", "#FFFFFF", "#FFD3D3", "#C9302C", "#212121"],
    textDensity: "Medium",
    visualType: "라이프스타일",
    themes: ["전문가", "신뢰"],
    landingUrl: "https://yeolda.com/premium",
    tags: ["프리미엄", "입주청소"],
  },
  {
    id: "yeolda-002",
    competitor: "yeolda",
    platform: "Meta",
    imageUrl: pic("yeolda2", 600, 750),
    aspectRatio: "4:5",
    copy: "정성을 담은 클리닝. 디테일이 다릅니다.",
    imageText: "DETAIL이 다르다",
    cta: "지금 신청",
    firstSeen: daysAgo(13),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 13,
    format: "이미지",
    dominantColors: ["#FF6B6B", "#FFFFFF", "#212121", "#FFD3D3", "#C9302C"],
    textDensity: "Medium",
    visualType: "제품샷",
    themes: ["전문가"],
    landingUrl: "https://yeolda.com/detail",
    tags: ["디테일"],
  },
  {
    id: "yeolda-003",
    competitor: "yeolda",
    platform: "TikTok",
    imageUrl: pic("yeolda3", 600, 1067),
    aspectRatio: "9:16",
    copy: "🌟 비포 애프터 충격주의. 이래서 열다인가요?",
    imageText: "충격! BEFORE/AFTER",
    cta: "구경하기",
    firstSeen: daysAgo(9),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 9,
    format: "동영상",
    dominantColors: ["#FF6B6B", "#FFFFFF", "#212121", "#7CB342", "#C9302C"],
    textDensity: "Heavy",
    visualType: "Before-After",
    themes: ["변화", "후기"],
    landingUrl: "https://yeolda.com/wow",
    tags: ["Before-After", "후기"],
  },
  {
    id: "yeolda-004",
    competitor: "yeolda",
    platform: "Meta",
    imageUrl: pic("yeolda4", 600, 600),
    aspectRatio: "1:1",
    copy: "신혼부부 80% 선택. 첫 집은 열다와 함께.",
    imageText: "신혼 80% 선택",
    cta: "신혼 패키지",
    firstSeen: daysAgo(17),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 17,
    format: "이미지",
    dominantColors: ["#FF6B6B", "#FFB6C1", "#FFFFFF", "#FFD3D3", "#C9302C"],
    textDensity: "Heavy",
    visualType: "인포그래픽",
    themes: ["가족", "후기"],
    landingUrl: "https://yeolda.com/newlywed",
    tags: ["신혼"],
  },
  {
    id: "yeolda-005",
    competitor: "yeolda",
    platform: "Google",
    imageUrl: pic("yeolda5", 1200, 675),
    aspectRatio: "16:9",
    copy: "5월 한정 신혼 청소 패키지 25% 할인.",
    imageText: "5월 한정 -25%",
    cta: "할인 받기",
    firstSeen: daysAgo(4),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 4,
    format: "이미지",
    dominantColors: ["#FF6B6B", "#FFFFFF", "#FFD3D3", "#C9302C", "#FFC940"],
    textDensity: "Heavy",
    visualType: "인포그래픽",
    themes: ["할인"],
    landingUrl: "https://yeolda.com/may",
    tags: ["할인", "5월"],
  },
  {
    id: "yeolda-006",
    competitor: "yeolda",
    platform: "Meta",
    imageUrl: pic("yeolda6", 600, 1067),
    aspectRatio: "9:16",
    copy: "엄마처럼 꼼꼼하게. 열다 매니저의 청소 일지.",
    imageText: "엄마처럼 꼼꼼히",
    cta: "예약하기",
    firstSeen: daysAgo(1),
    lastSeen: daysAgo(0),
    isActive: true,
    lifespanDays: 1,
    format: "동영상",
    dominantColors: ["#FF6B6B", "#FFFFFF", "#FFD3D3", "#A8895A", "#C9302C"],
    textDensity: "Minimal",
    visualType: "인물",
    themes: ["가족", "전문가"],
    landingUrl: "https://yeolda.com/diary",
    tags: ["스토리"],
  },
];

// Calendar heatmap data for last 8 weeks
function genCalendar(): CalendarPoint[] {
  const out: CalendarPoint[] = [];
  const ids: CompetitorId[] = ["miso", "soomgo", "laundrygo", "yeolda"];
  for (let day = 0; day < 56; day++) {
    const date = daysAgo(55 - day);
    for (const c of ids) {
      const base =
        c === "miso" ? 2.5 : c === "soomgo" ? 2 : c === "laundrygo" ? 1.5 : 1;
      const isWeekend = new Date(date).getDay() % 6 === 0;
      const noise = Math.random();
      const count = Math.max(0, Math.round(base + (isWeekend ? 1.5 : 0) - noise * 1.5));
      out.push({ competitor: c, date, count });
    }
  }
  return out;
}

export const calendarData = genCalendar();

export const insights: InsightCardData[] = [
  {
    competitor: "miso",
    title: "노란 톤 압도적",
    body: "광고 70%가 따뜻한 노랑/오렌지 계열로 통일. 브랜드 색을 시각적 hook으로 활용.",
    highlight: "70%",
  },
  {
    competitor: "miso",
    title: "후기 강조 전략",
    body: "이미지 25% 이상이 평점·후기 수치를 헤드라인으로 사용. 신뢰 시그널 강조.",
    highlight: "25%+",
  },
  {
    competitor: "soomgo",
    title: "차가운 블루 + 인포그래픽",
    body: "광고 60%가 인포그래픽 형식. 견적 비교라는 합리적 가치를 시각적으로 전달.",
    highlight: "60%",
  },
  {
    competitor: "soomgo",
    title: "텍스트 헤비 광고 다수",
    body: "이미지 안 텍스트가 Heavy인 비율이 4사 중 가장 높음 (50%). 정보 전달 중심.",
    highlight: "50%",
  },
  {
    competitor: "laundrygo",
    title: "민트색 + Before/After",
    body: "Before-After 비주얼이 광고 33%. '변화'를 일관되게 강조하는 전략.",
    highlight: "33%",
  },
  {
    competitor: "yeolda",
    title: "분홍·붉은 톤 + 신혼 타겟",
    body: "광고 50% 이상이 신혼/가족 테마. 따뜻한 색감으로 감성 어필.",
    highlight: "50%+",
  },
];

export const wordcloudData: WordFreq[] = [
  { competitor: "miso", word: "청소", count: 28 },
  { competitor: "miso", word: "할인", count: 18 },
  { competitor: "miso", word: "예약", count: 15 },
  { competitor: "miso", word: "전문가", count: 12 },
  { competitor: "miso", word: "후기", count: 11 },
  { competitor: "miso", word: "정기", count: 10 },
  { competitor: "miso", word: "워킹맘", count: 9 },
  { competitor: "miso", word: "신규", count: 8 },
  { competitor: "miso", word: "에어컨", count: 7 },
  { competitor: "miso", word: "입주", count: 6 },
  { competitor: "soomgo", word: "견적", count: 32 },
  { competitor: "soomgo", word: "비교", count: 22 },
  { competitor: "soomgo", word: "전문가", count: 18 },
  { competitor: "soomgo", word: "고수", count: 15 },
  { competitor: "soomgo", word: "검증", count: 13 },
  { competitor: "soomgo", word: "리얼", count: 11 },
  { competitor: "soomgo", word: "매칭", count: 10 },
  { competitor: "soomgo", word: "후기", count: 9 },
  { competitor: "soomgo", word: "이사", count: 7 },
  { competitor: "soomgo", word: "신혼", count: 6 },
  { competitor: "laundrygo", word: "비대면", count: 24 },
  { competitor: "laundrygo", word: "구독", count: 18 },
  { competitor: "laundrygo", word: "친환경", count: 14 },
  { competitor: "laundrygo", word: "프리미엄", count: 12 },
  { competitor: "laundrygo", word: "호텔식", count: 10 },
  { competitor: "laundrygo", word: "주말", count: 8 },
  { competitor: "laundrygo", word: "정기", count: 7 },
  { competitor: "laundrygo", word: "할인", count: 6 },
  { competitor: "yeolda", word: "신혼", count: 26 },
  { competitor: "yeolda", word: "프리미엄", count: 18 },
  { competitor: "yeolda", word: "디테일", count: 14 },
  { competitor: "yeolda", word: "엄마", count: 11 },
  { competitor: "yeolda", word: "꼼꼼", count: 10 },
  { competitor: "yeolda", word: "VIP", count: 8 },
  { competitor: "yeolda", word: "감동", count: 7 },
  { competitor: "yeolda", word: "5월", count: 6 },
];

export const alerts: AlertItem[] = [
  {
    id: "a1",
    date: daysAgo(0),
    competitor: "yeolda",
    message: "신규 광고 1건 발견 — \"엄마처럼 꼼꼼히\"",
    type: "new_ad",
  },
  {
    id: "a2",
    date: daysAgo(1),
    competitor: "laundrygo",
    message: "TikTok 광고 활성화 (라이프스타일)",
    type: "new_ad",
  },
  {
    id: "a3",
    date: daysAgo(2),
    competitor: "miso",
    message: "장수 광고 종료 — '전문 매니저 보장' (43일)",
    type: "stopped",
  },
  {
    id: "a4",
    date: daysAgo(3),
    competitor: "miso",
    message: "신규 후기 광고 (★4.9 / 5만+) 활성화",
    type: "new_ad",
  },
  {
    id: "a5",
    date: daysAgo(4),
    competitor: "yeolda",
    message: "5월 한정 -25% 할인 광고 시작",
    type: "new_ad",
  },
];

export function getCompetitor(id: CompetitorId): Competitor {
  return competitors.find((c) => c.id === id)!;
}
